version: '3.1'
networks:
  app-net:
    driver: bridge
services:
  chat:
    container_name: chat_app
    build:
      context: .
      dockerfile: ./src/Docker/Dockerfile             
    ports:
      - '3000:3000'
    environment:
      - DB_URL=postgres://postgres:postgres@database:5432/chats 
      - DB_TYPE=postgres 
    networks:
      - app-net 
    
  database:
    container_name: paymentsDB
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
      - POSTGRES_PASSWORD=password 
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments
    volumes:
      - local_pgdata:/var/lib/postgresql/data  
    ports :
      - "5432:5432" 
    networks:
      - app-net   
  dbadmin:
    container_name: PGAdmin
    image: dpage/pgadmin4    
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin   
    networks:
      - app-net           
volumes:
  local_pgdata:
  pgadmin-data:  